version: "2.1"
services:
  elasticsearch-base:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"

  kibana-base:
    image: docker.elastic.co/kibana/kibana:7.1.1
    ports:
      - "5601:5601"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      kibana.index: "aether-demo-2"

  es-consumer-base:
    image: ehealthafrica/elasticsearch-consumer:2.0-rc
    stdin_open: true
    ports:
      - "9009:9009"
    volumes:
     - ./conf:/code/conf/consumer
     - ./es_index:/code/es_index

    environment:
     - PYTHONUNBUFFERED=0
    command: start
